// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package s3

import (
	"github.com/golifez/go-aws-ctl-v2/api/s3"
)

type ControllerV1 struct{}

func NewV1() s3.IS3V1 {
	return &ControllerV1{}
}
